version: '3.8'

services:
  # 1. API 서버 컨테이너
  fastapi-app:
    build: .
    container_name: my-pdf-app
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    env_file:
      - .env

    volumes:
      - ./public/downloads:/usr/src/public/downloads
    ports:
      - "3000:3000"
    networks:      
      - cld-net
    depends_on:
      - redis
    command: ["node", "src/app.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    stop_grace_period: 30s


  # 2. Worker 전용 컨테이너
  pdf-worker:
    build: .
    container_name: my-pdf-worker
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - SERVER_URL=http://fastapi-app:3000
    volumes:
      - ./public/downloads:/usr/src/public/downloads
    networks:      
      - cld-net
    depends_on:
      - redis
    command: ["node", "src/worker.js"]
    stop_grace_period: 30s

  # 3 4. Redis
  redis:
    image: redis:alpine
    container_name: my-pdf-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cld-net


networks:
  cld-net:
    external: true